/**
 * @file Version.h
 * @brief Version information for SSD1315.
 *
 * This file is AUTO-GENERATED by scripts/generate_version.py from library.json.
 * DO NOT EDIT MANUALLY. Update version metadata via library.json or
 * scripts/generate_version.py bump/set commands.
 */

#pragma once

#include <stdint.h>

#ifndef SSD1315_VERSION_STRING
#define SSD1315_VERSION_STRING "1.1.0"
#endif

#ifndef SSD1315_BUILD_DATE
#define SSD1315_BUILD_DATE __DATE__
#endif

#ifndef SSD1315_BUILD_TIME
#define SSD1315_BUILD_TIME __TIME__
#endif

#ifndef SSD1315_BUILD_TIMESTAMP
#define SSD1315_BUILD_TIMESTAMP SSD1315_BUILD_DATE " " SSD1315_BUILD_TIME
#endif

#ifndef SSD1315_GIT_COMMIT
#define SSD1315_GIT_COMMIT "unknown"
#endif

#ifndef SSD1315_GIT_STATUS
#define SSD1315_GIT_STATUS "unknown"
#endif

#ifndef SSD1315_VERSION_FULL
#define SSD1315_VERSION_FULL SSD1315_VERSION_STRING " (" SSD1315_GIT_COMMIT ", " SSD1315_BUILD_TIMESTAMP ", " SSD1315_GIT_STATUS ")"
#endif

namespace SSD1315 {

/// @brief Major version (breaking changes).
static constexpr uint16_t VERSION_MAJOR = 1;

/// @brief Minor version (backward-compatible features).
static constexpr uint16_t VERSION_MINOR = 1;

/// @brief Patch version (backward-compatible fixes).
static constexpr uint16_t VERSION_PATCH = 0;

/// @brief Full semantic version string.
static constexpr const char* VERSION = SSD1315_VERSION_STRING;

/// @brief Encoded version for numeric comparison: MAJOR*10000 + MINOR*100 + PATCH.
static constexpr uint32_t VERSION_CODE = 10100;

/// @brief Backward-compatible alias used by older repositories.
static constexpr int VERSION_INT = 10100;

/// @brief Build date string.
static constexpr const char* BUILD_DATE = SSD1315_BUILD_DATE;

/// @brief Build time string.
static constexpr const char* BUILD_TIME = SSD1315_BUILD_TIME;

/// @brief Build timestamp string.
static constexpr const char* BUILD_TIMESTAMP = SSD1315_BUILD_TIMESTAMP;

/// @brief Git commit string.
static constexpr const char* GIT_COMMIT = SSD1315_GIT_COMMIT;

/// @brief Git working tree status string.
static constexpr const char* GIT_STATUS = SSD1315_GIT_STATUS;

/// @brief Full version string with build metadata.
static constexpr const char* VERSION_FULL = SSD1315_VERSION_FULL;

}  // namespace SSD1315

namespace ssd1315 = SSD1315;
