/**
 * @file Version.h
 * @brief Version information for SSD1315.
 *
 * This file is AUTO-GENERATED by scripts/generate_version.py from library.json.
 * DO NOT EDIT MANUALLY. Update version metadata via library.json or
 * scripts/generate_version.py bump/set commands.
 *
 * The SSD1315_* macros below are compile-time override hooks for build
 * metadata. The supported public API is the namespace static constexpr values.
 */

#pragma once

#include <stdint.h>

// Ignore obsolete command-line overrides so every version representation stays
// synchronized with library.json.
#ifdef SSD1315_VERSION_STRING
#undef SSD1315_VERSION_STRING
#endif
/// @brief Canonical semantic version generated from library.json.
#define SSD1315_VERSION_STRING "4.0.2"

#ifndef SSD1315_BUILD_DATE
/// @brief Compile-time build-date override; defaults to "unknown".
#define SSD1315_BUILD_DATE "unknown"
#endif

#ifndef SSD1315_BUILD_TIME
/// @brief Compile-time build-time override; defaults to "unknown".
#define SSD1315_BUILD_TIME "unknown"
#endif

#ifndef SSD1315_BUILD_TIMESTAMP
/// @brief Compile-time UTC build-timestamp override; defaults to "unknown".
#define SSD1315_BUILD_TIMESTAMP "unknown"
#endif

#ifndef SSD1315_GIT_COMMIT
/// @brief Compile-time source-revision override; defaults to "unknown".
#define SSD1315_GIT_COMMIT "unknown"
#endif

#ifndef SSD1315_GIT_STATUS
/// @brief Compile-time source-tree status override; defaults to "unknown".
#define SSD1315_GIT_STATUS "unknown"
#endif

// VERSION_FULL is canonical composition, not an independent metadata input.
#ifdef SSD1315_VERSION_FULL
#undef SSD1315_VERSION_FULL
#endif
/// @brief Full version composed from the canonical version and build metadata.
#define SSD1315_VERSION_FULL SSD1315_VERSION_STRING " (" SSD1315_GIT_COMMIT ", " SSD1315_BUILD_TIMESTAMP ", " SSD1315_GIT_STATUS ")"

namespace SSD1315 {

/// @brief Major version (breaking changes).
static constexpr uint16_t VERSION_MAJOR = 4;

/// @brief Minor version (backward-compatible features).
static constexpr uint16_t VERSION_MINOR = 0;

/// @brief Patch version (backward-compatible fixes).
static constexpr uint16_t VERSION_PATCH = 2;

/// @brief Full semantic version string.
static constexpr const char* VERSION = SSD1315_VERSION_STRING;

/// @brief Encoded version for numeric comparison: MAJOR*10000 + MINOR*100 + PATCH.
static constexpr uint32_t VERSION_CODE = 40002;

/// @brief Backward-compatible numeric-version alias used by older repositories.
/// @deprecated Use VERSION_CODE; retained for source compatibility.
static constexpr int VERSION_INT = 40002;

/// @brief Build date string.
static constexpr const char* BUILD_DATE = SSD1315_BUILD_DATE;

/// @brief Build time string.
static constexpr const char* BUILD_TIME = SSD1315_BUILD_TIME;

/// @brief Build timestamp string.
static constexpr const char* BUILD_TIMESTAMP = SSD1315_BUILD_TIMESTAMP;

/// @brief Git commit string.
static constexpr const char* GIT_COMMIT = SSD1315_GIT_COMMIT;

/// @brief Git working tree status string.
static constexpr const char* GIT_STATUS = SSD1315_GIT_STATUS;

/// @brief Full version string with build metadata.
static constexpr const char* VERSION_FULL = SSD1315_VERSION_FULL;

}  // namespace SSD1315

namespace ssd1315 = SSD1315;
